# -*- coding: utf-8 -*-
"""Milestone4 (Ai Lab) Testing Pipeline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KPfpkrcJGFbTYsj7o0sd77AORU8YkJk1
"""

from google.colab import drive
drive.mount('/content/drive')

"""**Checking Class Imbalance**"""

import os
import pandas as pd
import matplotlib.pyplot as plt

# =====================================================
# DATASET PATH
# =====================================================
DATASET_PATH = "/content/drive/MyDrive/Milestone2(AI LAB)/final_dataset"

IMAGE_EXTENSIONS = (".jpg", ".jpeg", ".png", ".bmp", ".tif", ".tiff", ".webp")

splits = ["train", "val", "test"]

class_counts = {}

# =====================================================
# COUNT IMAGES FROM TRAIN + VAL + TEST
# =====================================================
for split in splits:

    split_path = os.path.join(DATASET_PATH, split)

    for class_name in os.listdir(split_path):

        class_path = os.path.join(split_path, class_name)

        if os.path.isdir(class_path):

            count = sum(
                1
                for file in os.listdir(class_path)
                if file.lower().endswith(IMAGE_EXTENSIONS)
            )

            class_counts[class_name] = class_counts.get(class_name, 0) + count

# =====================================================
# CREATE TABLE
# =====================================================
df = pd.DataFrame({
    "Class": class_counts.keys(),
    "Images": class_counts.values()
})

df = df.sort_values("Class").reset_index(drop=True)

total_images = df["Images"].sum()
df["Percentage"] = (df["Images"] / total_images * 100).round(2)

print("\nDataset Statistics\n")
print(df)

print("\nTotal Images :", total_images)
print("Total Classes:", len(df))

# =====================================================
# BAR CHART
# =====================================================
plt.figure(figsize=(10,5))

bars = plt.bar(df["Class"], df["Images"])

plt.title("Images per Class")
plt.xlabel("Class")
plt.ylabel("Number of Images")

plt.xticks(rotation=20)

for bar in bars:
    plt.text(
        bar.get_x()+bar.get_width()/2,
        bar.get_height(),
        int(bar.get_height()),
        ha='center',
        va='bottom'
    )

plt.tight_layout()
plt.show()

# =====================================================
# BALANCE ANALYSIS
# =====================================================
max_images = df["Images"].max()
min_images = df["Images"].min()

imbalance_ratio = max_images / min_images

print("\n==============================")
print("Dataset Balance Analysis")
print("==============================")

print(f"Largest Class  : {max_images}")
print(f"Smallest Class : {min_images}")
print(f"Imbalance Ratio: {imbalance_ratio:.2f}:1")

std = df["Images"].std()
mean = df["Images"].mean()
cv = std / mean

print(f"Coefficient of Variation (CV): {cv:.2f}")

if imbalance_ratio <= 2:
    print("\n✅ WELL BALANCED")
    print("No balancing is required.")

elif imbalance_ratio <= 3:
    print("\n🟡 MODERATELY BALANCED")
    print("Training should work fine.")
    print("Consider mild augmentation.")

elif imbalance_ratio <= 5:
    print("\n🟠 IMBALANCED")
    print("Recommended:")
    print("• Data Augmentation")
    print("• Class Weights")
    print("• WeightedRandomSampler")

else:
    print("\n🔴 HIGHLY IMBALANCED")
    print("Strongly Recommended:")
    print("• Collect More Images")
    print("• Heavy Augmentation")
    print("• Class Weights")
    print("• WeightedRandomSampler")

# =====================================================
# TRAIN / VAL / TEST DISTRIBUTION
# =====================================================
print("\n==============================")
print("Train / Validation / Test Distribution")
print("==============================")

for split in splits:

    print(f"\n{split.upper()}")

    split_total = 0

    split_path = os.path.join(DATASET_PATH, split)

    for class_name in sorted(os.listdir(split_path)):

        class_path = os.path.join(split_path, class_name)

        if os.path.isdir(class_path):

            count = len([
                f for f in os.listdir(class_path)
                if f.lower().endswith(IMAGE_EXTENSIONS)
            ])

            split_total += count

            print(f"{class_name:<20} {count}")

    print(f"Total {split}: {split_total}")

"""**Taking 20% dataset from the original data**



"""

import os
import random
import shutil

# ==============================
# Configuration
# ==============================

# Original dataset
SOURCE_DATASET = "/content/drive/MyDrive/Milestone2(AI LAB)/final_dataset (1)"

# New 20% dataset
DEST_DATASET = "/content/drive/MyDrive/Driver_Activity_Dataset_20Percent(1)"

# Percentage to keep
PERCENTAGE = 0.20

# Reproducibility
random.seed(42)

IMAGE_EXTENSIONS = (
    ".jpg", ".jpeg", ".png",
    ".bmp", ".tif", ".tiff"
)

# ==============================
# Copy Dataset
# ==============================

splits = ["train", "val", "test"]

# Create destination directories
os.makedirs(DEST_DATASET, exist_ok=True)

for split in splits:

    split_path = os.path.join(SOURCE_DATASET, split)

    # Skip if split doesn't exist
    if not os.path.exists(split_path):
        print(f"⚠️ Split '{split}' not found at {split_path} - skipping")
        continue

    # Get all classes in this split
    try:
        classes = sorted(os.listdir(split_path))
    except NotADirectoryError:
        print(f"⚠️ {split_path} is not a directory - skipping")
        continue

    for cls in classes:

        class_path = os.path.join(split_path, cls)

        if not os.path.isdir(class_path):
            continue

        # Get all images
        try:
            images = [
                img for img in os.listdir(class_path)
                if img.lower().endswith(IMAGE_EXTENSIONS)
            ]
        except FileNotFoundError:
            print(f"⚠️ Class path not found: {class_path} - skipping")
            continue

        total_images = len(images)

        # Skip empty directories
        if total_images == 0:
            print(f"{split}/{cls}")
            print(f"⚠️ No images found - skipping")
            print("-"*40)
            continue

        # Calculate sample size (minimum 1)
        sample_size = max(1, int(total_images * PERCENTAGE))

        # Sample images
        sampled_images = random.sample(images, sample_size)

        # Create destination folder
        destination_folder = os.path.join(
            DEST_DATASET,
            split,
            cls
        )

        os.makedirs(destination_folder, exist_ok=True)

        # Copy images with error handling
        success_count = 0
        for image in sampled_images:

            src = os.path.join(class_path, image)
            dst = os.path.join(destination_folder, image)

            try:
                shutil.copy2(src, dst)
                success_count += 1
            except FileNotFoundError:
                print(f"⚠️ File not found: {src} - skipping")
            except Exception as e:
                print(f"⚠️ Error copying {src}: {e} - skipping")

        print(f"{split}/{cls}")
        print(f"Original : {total_images}")
        print(f"Copied   : {success_count} / {sample_size}")
        print("-"*40)

# ==============================
# Summary
# ==============================
print("\n" + "="*50)
print("DATASET CREATION SUMMARY")
print("="*50)

# Count files in destination
total_files = 0
for root, dirs, files in os.walk(DEST_DATASET):
    for file in files:
        if file.lower().endswith(IMAGE_EXTENSIONS):
            total_files += 1

print(f"\n✅ Total images copied: {total_files}")
print(f"✅ Destination: {DEST_DATASET}")

# Show per-split statistics
for split in splits:
    split_path = os.path.join(DEST_DATASET, split)
    if os.path.exists(split_path):
        count = 0
        for root, dirs, files in os.walk(split_path):
            for file in files:
                if file.lower().endswith(IMAGE_EXTENSIONS):
                    count += 1
        print(f"   {split}: {count} images")

print("\n✅ 20% candidate dataset created successfully!")

pip install torch torchvision scikit-learn tqdm pandas matplotlib

"""**Training Model on 20% data on 5 epoch**"""

import torch
import torchvision
from torchvision import datasets, transforms
from torch.utils.data import DataLoader
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from tqdm import tqdm
import pandas as pd

# -----------------------
# Configuration
# -----------------------

DEVICE = "cuda" if torch.cuda.is_available() else "cpu"

BATCH_SIZE = 32

VAL_DIR = "/content/drive/MyDrive/Driver_Activity_Dataset_20Percent(1)/val"

NUM_CLASSES = 5

# -----------------------
# Validation Transform
# -----------------------

transform = transforms.Compose([
    transforms.Resize((224,224)),
    transforms.ToTensor(),
    transforms.Normalize(
        mean=[0.485,0.456,0.406],
        std=[0.229,0.224,0.225]
    )
])

val_dataset = datasets.ImageFolder(
    VAL_DIR,
    transform=transform
)

val_loader = DataLoader(
    val_dataset,
    batch_size=BATCH_SIZE,
    shuffle=False
)

print(val_dataset.classes)

def evaluate_model(model):

    model.eval()

    preds = []
    labels = []

    with torch.no_grad():

        for images, target in tqdm(val_loader):

            images = images.to(DEVICE)
            target = target.to(DEVICE)

            outputs = model(images)

            prediction = outputs.argmax(1)

            preds.extend(prediction.cpu().numpy())
            labels.extend(target.cpu().numpy())

    acc = accuracy_score(labels, preds)

    precision = precision_score(
        labels,
        preds,
        average='weighted',
        zero_division=0
    )

    recall = recall_score(
        labels,
        preds,
        average='weighted'
    )

    f1 = f1_score(
        labels,
        preds,
        average='weighted'
    )

    return acc, precision, recall, f1

"""**MobileNetV3**"""

weights = torchvision.models.MobileNet_V3_Large_Weights.DEFAULT

model = torchvision.models.mobilenet_v3_large(weights=weights)

model.classifier[3] = torch.nn.Linear(
    model.classifier[3].in_features,
    NUM_CLASSES
)

model = model.to(DEVICE)

mobile_results = evaluate_model(model)

"""**ResNet50**"""

weights = torchvision.models.ResNet50_Weights.DEFAULT

model = torchvision.models.resnet50(weights=weights)

model.fc = torch.nn.Linear(
    model.fc.in_features,
    NUM_CLASSES
)

model = model.to(DEVICE)

resnet_results = evaluate_model(model)

"""**EfficientNet-B0**"""

weights = torchvision.models.EfficientNet_B0_Weights.DEFAULT

model = torchvision.models.efficientnet_b0(weights=weights)

model.classifier[1] = torch.nn.Linear(
    model.classifier[1].in_features,
    NUM_CLASSES
)

model = model.to(DEVICE)

efficient_results = evaluate_model(model)

comparison = pd.DataFrame({

    "Model":[
        "MobileNetV3",
        "ResNet50",
        "EfficientNet-B0"
    ],

    "Accuracy":[
        mobile_results[0],
        resnet_results[0],
        efficient_results[0]
    ],

    "Precision":[
        mobile_results[1],
        resnet_results[1],
        efficient_results[1]
    ],

    "Recall":[
        mobile_results[2],
        resnet_results[2],
        efficient_results[2]
    ],

    "F1 Score":[
        mobile_results[3],
        resnet_results[3],
        efficient_results[3]
    ]
})

print(comparison)

comparison.to_csv("baseline_comparison.csv", index=False)

import copy
import time
import torch
import torch.nn as nn
import torch.optim as optim

from torchvision import datasets, transforms, models
from torch.utils.data import DataLoader

from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_recall_fscore_support

import pandas as pd
from tqdm import tqdm

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

print(device)

train_dir = "/content/drive/MyDrive/Driver_Activity_Dataset_20Percent(1)/train"
val_dir = "/content/drive/MyDrive/Driver_Activity_Dataset_20Percent(1)/val"

transform_train = transforms.Compose([
    transforms.Resize((224,224)),
    transforms.RandomHorizontalFlip(),
    transforms.ToTensor(),
])

transform_val = transforms.Compose([
    transforms.Resize((224,224)),
    transforms.ToTensor(),
])

train_dataset = datasets.ImageFolder(train_dir, transform_train)
val_dataset = datasets.ImageFolder(val_dir, transform_val)

train_loader = DataLoader(train_dataset,
                          batch_size=32,
                          shuffle=True)

val_loader = DataLoader(val_dataset,
                        batch_size=32,
                        shuffle=False)

num_classes = len(train_dataset.classes)

print(train_dataset.classes)

def get_model(name):

    if name=="MobileNetV3":

        model = models.mobilenet_v3_large(weights="DEFAULT")
        in_features = model.classifier[3].in_features
        model.classifier[3] = nn.Linear(in_features,num_classes)

    elif name=="ResNet50":

        model = models.resnet50(weights="DEFAULT")
        in_features = model.fc.in_features
        model.fc = nn.Linear(in_features,num_classes)

    elif name=="EfficientNetB0":

        model = models.efficientnet_b0(weights="DEFAULT")
        in_features = model.classifier[1].in_features
        model.classifier[1] = nn.Linear(in_features,num_classes)

    return model.to(device)

def train_one_model(model):

    criterion = nn.CrossEntropyLoss()

    optimizer = optim.AdamW(model.parameters(),lr=0.001)

    epochs = 15

    model.train()

    for epoch in range(epochs):

        running_loss=0

        for images,labels in tqdm(train_loader):

            images=images.to(device)
            labels=labels.to(device)

            optimizer.zero_grad()

            outputs=model(images)

            loss=criterion(outputs,labels)

            loss.backward()

            optimizer.step()

            running_loss+=loss.item()

        print(f"Epoch {epoch+1} Loss={running_loss/len(train_loader):.4f}")

def evaluate(model):

    model.eval()

    preds=[]
    labels_list=[]

    with torch.no_grad():

        for images,labels in val_loader:

            images=images.to(device)

            outputs=model(images)

            pred=torch.argmax(outputs,1)

            preds.extend(pred.cpu().numpy())

            labels_list.extend(labels.numpy())

    accuracy=accuracy_score(labels_list,preds)

    precision,recall,f1,_=precision_recall_fscore_support(
        labels_list,
        preds,
        average="weighted"
    )

    return accuracy,precision,recall,f1

model_names = [
    "MobileNetV3",
    "ResNet50",
    "EfficientNetB0"
]

results=[]

for name in model_names:

    print("="*60)
    print(name)

    model=get_model(name)

    train_one_model(model)

    acc,pre,rec,f1=evaluate(model)

    results.append([name,acc,pre,rec,f1])

df=pd.DataFrame(results,
columns=[
    "Model",
    "Accuracy",
    "Precision",
    "Recall",
    "F1 Score"
])

print(df)

import matplotlib.pyplot as plt
import pandas as pd

data = {
"Experiment":["Baseline","LR=0.0005","LR=0.0001","BS=16","BS=64","SGD","AdamW"],
"Accuracy":[93.98,91.67,93.98,91.20,95.83,39.35,90.27]
}

df=pd.DataFrame(data)

plt.figure(figsize=(8,5))
plt.plot(df["Experiment"],df["Accuracy"],marker='o')
plt.xticks(rotation=30)
plt.ylabel("Accuracy (%)")
plt.title("Hyperparameter Comparison")
plt.grid(True)
plt.show()

import pandas as pd
import matplotlib.pyplot as plt

# ----------------------------------------------------
# Hyperparameter Experiment Results (Best model of each experiment)
# ----------------------------------------------------
data = {
    "Experiment": [
        "Baseline\nAdam\nLR=0.001\nBS=32",
        "LR=0.0005",
        "LR=0.0001",
        "BS=16",
        "BS=64",
        "SGD",
        "AdamW"
    ],

    "Accuracy": [
        93.98,
        91.67,
        93.98,
        91.20,
        95.83,
        39.35,
        90.28
    ],

    "Precision": [
        94.08,
        91.91,
        94.11,
        91.57,
        95.89,
        43.36,
        90.43
    ],

    "Recall": [
        93.98,
        91.67,
        93.98,
        91.20,
        95.83,
        39.35,
        90.28
    ],

    "F1 Score": [
        93.98,
        91.68,
        94.02,
        91.22,
        95.81,
        35.90,
        90.10
    ]
}

df = pd.DataFrame(data)

# ----------------------------------------------------
# Plot Function
# ----------------------------------------------------
def plot_metric(metric):
    plt.figure(figsize=(9,5))

    plt.plot(
        df["Experiment"],
        df[metric],
        marker='o',
        linewidth=2,
        markersize=8
    )

    plt.title(f"{metric} Comparison Across Hyperparameter Experiments",
              fontsize=14)

    plt.ylabel(metric + " (%)")
    plt.xlabel("Experiments")

    plt.xticks(rotation=20)

    plt.grid(True)

    # Display values above points
    for x, y in zip(df["Experiment"], df[metric]):
        plt.text(x, y+0.5, f"{y:.2f}",
                 ha='center',
                 fontsize=9)

    plt.tight_layout()
    plt.show()


# ----------------------------------------------------
# Generate all plots
# ----------------------------------------------------
plot_metric("Accuracy")
plot_metric("Precision")
plot_metric("Recall")
plot_metric("F1 Score")

import matplotlib.pyplot as plt
import numpy as np

models = ["MobileNetV3", "ResNet50", "EfficientNet-B0"]

accuracy = [89.35, 92.13, 93.98]
precision = [89.74, 92.32, 94.08]
recall = [89.35, 92.13, 93.98]
f1 = [89.39, 92.14, 93.98]

x = np.arange(len(models))
width = 0.2

plt.figure(figsize=(10,6))

plt.bar(x-width*1.5, accuracy, width, label='Accuracy')
plt.bar(x-width/2, precision, width, label='Precision')
plt.bar(x+width/2, recall, width, label='Recall')
plt.bar(x+width*1.5, f1, width, label='F1 Score')

plt.xticks(x, models, fontsize=12)
plt.ylabel("Percentage (%)", fontsize=12)
plt.ylim(0,100)
plt.title("Performance Comparison of Candidate Models")
plt.legend()

plt.tight_layout()
plt.savefig("model_comparison.png", dpi=300)
plt.show()

import matplotlib.pyplot as plt

experiments = [
    "Baseline",
    "LR=0.0005",
    "LR=0.0001",
    "BS=16",
    "BS=64",
    "SGD",
    "AdamW"
]

accuracy = [87.04,90.74,87.96,87.96,68.06,42.13,89.81]

plt.figure(figsize=(10,5))

plt.plot(experiments, accuracy, marker='o', linewidth=2)

for i,v in enumerate(accuracy):
    plt.text(i,v+0.6,str(v),ha='center')

plt.ylabel("Accuracy (%)")
plt.xlabel("Experiment")
plt.title("MobileNetV3 Hyperparameter Comparison")
plt.grid(True)

plt.tight_layout()
plt.savefig("hyperparameter_comparison.png",dpi=300)
plt.show()

import matplotlib.pyplot as plt
import numpy as np

metrics = ["Accuracy","Precision","Recall","F1"]

data = np.array([
    [89.35,89.74,89.35,89.39],
    [92.13,92.32,92.13,92.14],
    [93.98,94.08,93.98,93.98]
])

models = ["MobileNetV3","ResNet50","EfficientNet-B0"]

fig, ax = plt.subplots(figsize=(7,4))

im = ax.imshow(data)

ax.set_xticks(np.arange(len(metrics)))
ax.set_yticks(np.arange(len(models)))

ax.set_xticklabels(metrics)
ax.set_yticklabels(models)

plt.title("Performance Heatmap")

for i in range(len(models)):
    for j in range(len(metrics)):
        ax.text(j, i, f"{data[i,j]:.2f}",
                ha="center", va="center", color="black")

plt.colorbar(im)

plt.tight_layout()
plt.savefig("performance_heatmap.png",dpi=300)
plt.show()

import numpy as np
import matplotlib.pyplot as plt

experiments = [
    "Baseline",
    "LR=5e-4",
    "LR=1e-4",
    "BS16",
    "BS64",
    "SGD",
    "AdamW"
]

accuracy = np.array([[87.04,90.74,87.96,87.96,68.06,42.13,89.81]])

fig, ax = plt.subplots(figsize=(10,2.5))
im = ax.imshow(accuracy)

ax.set_xticks(np.arange(len(experiments)))
ax.set_xticklabels(experiments, rotation=45)

ax.set_yticks([0])
ax.set_yticklabels(["Accuracy"])

for i in range(accuracy.shape[0]):
    for j in range(accuracy.shape[1]):
        ax.text(j, i, f"{accuracy[i,j]:.2f}",
                ha="center", va="center")

plt.colorbar(im)

plt.title("Hyperparameter Experiment Heatmap")

plt.tight_layout()
plt.show()

import torch
import torchvision.models as models

models_dict = {
    "MobileNetV3": models.mobilenet_v3_large(weights=None),
    "ResNet50": models.resnet50(weights=None),
    "EfficientNet-B0": models.efficientnet_b0(weights=None)
}

for name, model in models_dict.items():
    total = sum(p.numel() for p in model.parameters())
    trainable = sum(p.numel() for p in model.parameters() if p.requires_grad)

    print(f"{name}")
    print(f"Total Parameters: {total:,}")
    print(f"Trainable Parameters: {trainable:,}")
    print("-"*40)

pip install ptflops

from ptflops import get_model_complexity_info
import torchvision.models as models

models_dict = {
    "MobileNetV3": models.mobilenet_v3_large(weights=None),
    "ResNet50": models.resnet50(weights=None),
    "EfficientNet-B0": models.efficientnet_b0(weights=None)
}

for name, model in models_dict.items():

    macs, params = get_model_complexity_info(
        model,
        (3,224,224),
        as_strings=True,
        print_per_layer_stat=False,
        verbose=False
    )

    print(name)
    print("FLOPs (MACs):", macs)
    print("Parameters:", params)
    print()

import torch
import torchvision.models as models

device = torch.device("cuda")

dummy = torch.randn(1,3,224,224).to(device)

models_dict = {
    "MobileNetV3": models.mobilenet_v3_large(weights=None).to(device),
    "ResNet50": models.resnet50(weights=None).to(device),
    "EfficientNet-B0": models.efficientnet_b0(weights=None).to(device)
}

for name, model in models_dict.items():

    torch.cuda.empty_cache()

    torch.cuda.reset_peak_memory_stats()

    with torch.no_grad():
        model(dummy)

    mem = torch.cuda.max_memory_allocated()/1024**2

    print(name, mem,"MB")

import torch
import time
import torchvision.models as models

device = torch.device("cuda")

dummy = torch.randn(1,3,224,224).to(device)

models_dict = {
    "MobileNetV3": models.mobilenet_v3_large(weights=None).to(device),
    "ResNet50": models.resnet50(weights=None).to(device),
    "EfficientNet-B0": models.efficientnet_b0(weights=None).to(device)
}

for name, model in models_dict.items():

    model.eval()

    # warmup
    for _ in range(20):
        model(dummy)

    torch.cuda.synchronize()

    start = time.time()

    for _ in range(200):
        model(dummy)

    torch.cuda.synchronize()

    end = time.time()

    latency = (end-start)/200*1000

    fps = 1000/latency

    print(name)
    print("Latency:",latency,"ms")
    print("FPS:",fps)
    print()

from google.colab import drive
drive.mount('/content/drive')

"""**Training Pipeline**"""

# ============================================
# MobileNetV3 Training from Scratch with Checkpoint Support
# Dataset: Nested structure (train/val/test folders)
# Features:
#   - Train from scratch
#   - Save checkpoints every epoch
#   - Resume training from last checkpoint
#   - Early stopping
#   - Mixed precision training
# ============================================

import torch
import torch.nn as nn
import torch.optim as optim
from torchvision import datasets, transforms, models
from torch.utils.data import DataLoader
import matplotlib.pyplot as plt
import numpy as np
import os
import time
import json
from google.colab import drive
from sklearn.metrics import classification_report, confusion_matrix
import seaborn as sns
from torch.cuda.amp import autocast, GradScaler
import warnings
warnings.filterwarnings('ignore')

# ============================================
# 1. Mount Google Drive
# ============================================
drive.mount('/content/drive')

# ============================================
# 2. Configuration
# ============================================
class Config:
    # Data paths
    data_dir = '/content/drive/MyDrive/Milestone2(AI LAB)/final_dataset (1)'

    # Checkpoint path
    checkpoint_dir = '/content/drive/MyDrive/checkpoints'
    checkpoint_path = os.path.join(checkpoint_dir, 'mobilenetv3_checkpoint.pth')
    best_model_path = os.path.join(checkpoint_dir, 'best_mobilenetv3.pth')
    final_model_path = os.path.join(checkpoint_dir, 'final_mobilenetv3.pth')

    # Training parameters
    batch_size = 32
    num_workers = 2
    epochs = 50
    learning_rate = 0.0005
    weight_decay = 0.01
    patience = 7  # Early stopping patience

    # Model parameters
    input_size = 224
    num_classes = 5

    # Mixed precision
    use_amp = True

# Create checkpoint directory if it doesn't exist
os.makedirs(Config.checkpoint_dir, exist_ok=True)

# ============================================
# 3. Check for GPU
# ============================================
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

if device.type == 'cuda':
    print(f"GPU: {torch.cuda.get_device_name(0)}")
    print(f"GPU Memory: {torch.cuda.get_device_properties(0).total_memory / 1e9:.2f} GB")

# ============================================
# 4. Define Transforms
# ============================================
train_transform = transforms.Compose([
    transforms.Resize((Config.input_size, Config.input_size)),
    transforms.RandomHorizontalFlip(p=0.5),
    transforms.RandomRotation(10),
    transforms.ColorJitter(brightness=0.2, contrast=0.2, saturation=0.1),
    transforms.ToTensor(),
    transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
])

val_transform = transforms.Compose([
    transforms.Resize((Config.input_size, Config.input_size)),
    transforms.ToTensor(),
    transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
])

# ============================================
# 5. Load Dataset
# ============================================
print("\n" + "="*60)
print("LOADING DATASET...")
print("="*60)

train_dir = os.path.join(Config.data_dir, 'train')
val_dir = os.path.join(Config.data_dir, 'val')
test_dir = os.path.join(Config.data_dir, 'test')

print(f"Train folder exists: {os.path.exists(train_dir)}")
print(f"Val folder exists: {os.path.exists(val_dir)}")
print(f"Test folder exists: {os.path.exists(test_dir)}")

train_dataset = datasets.ImageFolder(root=train_dir, transform=train_transform)
val_dataset = datasets.ImageFolder(root=val_dir, transform=val_transform)
test_dataset = datasets.ImageFolder(root=test_dir, transform=val_transform)

# Display class mapping
print("\nCLASS MAPPING:")
print("-"*40)
class_names = train_dataset.classes
for idx, class_name in enumerate(class_names):
    print(f"  {idx}: {class_name}")

num_classes = len(class_names)
print(f"\nTotal classes: {num_classes}")
print(f"Training samples: {len(train_dataset)}")
print(f"Validation samples: {len(val_dataset)}")
print(f"Test samples: {len(test_dataset)}")

# Count images per class
print("\nIMAGES PER CLASS (TRAIN):")
print("-"*40)
for class_name in class_names:
    class_path = os.path.join(train_dir, class_name)
    if os.path.exists(class_path):
        count = len(os.listdir(class_path))
        print(f"  {class_name}: {count} images")

print("="*60 + "\n")

# ============================================
# 6. Create DataLoaders
# ============================================
train_loader = DataLoader(
    train_dataset,
    batch_size=Config.batch_size,
    shuffle=True,
    num_workers=Config.num_workers,
    pin_memory=True
)

val_loader = DataLoader(
    val_dataset,
    batch_size=Config.batch_size,
    shuffle=False,
    num_workers=Config.num_workers,
    pin_memory=True
)

test_loader = DataLoader(
    test_dataset,
    batch_size=Config.batch_size,
    shuffle=False,
    num_workers=Config.num_workers,
    pin_memory=True
)

print(f"✅ DataLoaders created successfully!")
print(f"   - Train batches: {len(train_loader)}")
print(f"   - Val batches: {len(val_loader)}")
print(f"   - Test batches: {len(test_loader)}")

# ============================================
# 7. Create Model
# ============================================
def create_model(num_classes, from_scratch=True):
    """
    Create MobileNetV3 model.
    If from_scratch=True, train from scratch (no pretrained weights).
    If from_scratch=False, use pretrained weights.
    """
    if from_scratch:
        print("\n" + "="*60)
        print("CREATING MODEL FROM SCRATCH...")
        print("="*60)
        # No pretrained weights - train from scratch
        model = models.mobilenet_v3_large(weights=None)
    else:
        print("\n" + "="*60)
        print("CREATING MODEL WITH PRETRAINED WEIGHTS...")
        print("="*60)
        # Use pretrained weights
        model = models.mobilenet_v3_large(weights='IMAGENET1K_V1')

    # Replace the classifier head
    model.classifier[3] = nn.Linear(in_features=1280, out_features=num_classes)

    return model

# Create model from scratch
model = create_model(num_classes, from_scratch=True)
model = model.to(device)

print(f"\nModel: MobileNetV3 Large")
print(f"Total parameters: {sum(p.numel() for p in model.parameters()):,}")
print(f"Trainable parameters: {sum(p.numel() for p in model.parameters() if p.requires_grad):,}")
print(f"Output classes: {num_classes}")

# ============================================
# 8. Define Loss, Optimizer, and Scheduler
# ============================================
criterion = nn.CrossEntropyLoss()

optimizer = optim.Adam(model.parameters(), lr=Config.learning_rate, weight_decay=Config.weight_decay)

scheduler = optim.lr_scheduler.ReduceLROnPlateau(
    optimizer,
    mode='min',
    factor=0.5,
    patience=3,
    min_lr=1e-6
)

scaler = GradScaler() if Config.use_amp else None

print(f"\nTraining Configuration:")
print(f"  - Training from: Scratch")
print(f"  - Optimizer: Adam")
print(f"  - Learning Rate: {Config.learning_rate}")
print(f"  - Weight Decay: {Config.weight_decay}")
print(f"  - Mixed Precision: {Config.use_amp}")
print(f"  - Epochs: {Config.epochs}")
print(f"  - Early Stopping Patience: {Config.patience}")

# ============================================
# 9. Checkpoint Functions
# ============================================
def save_checkpoint(epoch, model, optimizer, scheduler, scaler,
                    train_losses, val_losses, train_accuracies, val_accuracies,
                    best_val_acc, is_best=False):
    """
    Save checkpoint with all training state.
    """
    checkpoint = {
        'epoch': epoch,
        'model_state_dict': model.state_dict(),
        'optimizer_state_dict': optimizer.state_dict(),
        'scheduler_state_dict': scheduler.state_dict(),
        'scaler_state_dict': scaler.state_dict() if scaler else None,
        'train_losses': train_losses,
        'val_losses': val_losses,
        'train_accuracies': train_accuracies,
        'val_accuracies': val_accuracies,
        'best_val_acc': best_val_acc,
        'class_names': class_names,
        'num_classes': num_classes,
        'config': {
            'batch_size': Config.batch_size,
            'learning_rate': Config.learning_rate,
            'weight_decay': Config.weight_decay,
            'epochs': Config.epochs,
            'from_scratch': True
        }
    }

    # Save latest checkpoint
    torch.save(checkpoint, Config.checkpoint_path)
    print(f"  💾 Checkpoint saved at epoch {epoch+1}")

    # Save best model separately
    if is_best:
        torch.save({
            'epoch': epoch,
            'model_state_dict': model.state_dict(),
            'best_val_acc': best_val_acc,
            'class_names': class_names,
            'num_classes': num_classes
        }, Config.best_model_path)
        print(f"  ⭐ Best model saved with Val Acc: {best_val_acc:.2f}%")

    # Save metadata
    metadata = {
        'last_epoch': epoch,
        'best_val_acc': best_val_acc,
        'class_names': class_names,
        'num_classes': num_classes,
        'total_epochs': epoch + 1
    }
    with open(os.path.join(Config.checkpoint_dir, 'training_metadata.json'), 'w') as f:
        json.dump(metadata, f)

def load_checkpoint(model, optimizer, scheduler, scaler):
    """
    Load checkpoint and resume training.
    Returns: (start_epoch, train_losses, val_losses, train_accuracies, val_accuracies, best_val_acc)
    """
    if not os.path.exists(Config.checkpoint_path):
        print("No checkpoint found. Starting training from scratch.")
        return 0, [], [], [], [], 0.0

    print(f"\n🔄 Loading checkpoint from: {Config.checkpoint_path}")
    checkpoint = torch.load(Config.checkpoint_path, map_location=device)

    # Load model state
    model.load_state_dict(checkpoint['model_state_dict'])

    # Load optimizer state
    optimizer.load_state_dict(checkpoint['optimizer_state_dict'])

    # Load scheduler state
    scheduler.load_state_dict(checkpoint['scheduler_state_dict'])

    # Load scaler state
    if scaler and checkpoint['scaler_state_dict']:
        scaler.load_state_dict(checkpoint['scaler_state_dict'])

    # Load training history
    start_epoch = checkpoint['epoch'] + 1
    train_losses = checkpoint.get('train_losses', [])
    val_losses = checkpoint.get('val_losses', [])
    train_accuracies = checkpoint.get('train_accuracies', [])
    val_accuracies = checkpoint.get('val_accuracies', [])
    best_val_acc = checkpoint.get('best_val_acc', 0.0)

    print(f"  ✅ Resuming from epoch {start_epoch}")
    print(f"  📊 Best Validation Accuracy so far: {best_val_acc:.2f}%")

    return start_epoch, train_losses, val_losses, train_accuracies, val_accuracies, best_val_acc

def resume_training():
    """
    Check if checkpoint exists and prompt user to resume or start fresh.
    """
    if os.path.exists(Config.checkpoint_path):
        print("\n" + "="*60)
        print("🔄 CHECKPOINT FOUND!")
        print("="*60)
        checkpoint = torch.load(Config.checkpoint_path, map_location=device)
        print(f"  Last completed epoch: {checkpoint['epoch'] + 1}")
        print(f"  Best validation accuracy: {checkpoint.get('best_val_acc', 0.0):.2f}%")

        response = input("\nDo you want to resume training from this checkpoint? (y/n): ")
        if response.lower() == 'y':
            return True

    return False

# ============================================
# 10. Training Loop
# ============================================
def train_model(model, train_loader, val_loader, criterion, optimizer, scheduler, scaler):
    # Check for checkpoint
    resume = resume_training()

    if resume:
        start_epoch, train_losses, val_losses, train_accuracies, val_accuracies, best_val_acc = load_checkpoint(
            model, optimizer, scheduler, scaler
        )
    else:
        # Remove old checkpoint if starting fresh
        if os.path.exists(Config.checkpoint_path):
            os.remove(Config.checkpoint_path)
            print("🗑️ Removed old checkpoint. Starting fresh training.")
        start_epoch = 0
        train_losses = []
        val_losses = []
        train_accuracies = []
        val_accuracies = []
        best_val_acc = 0.0

    early_stop_counter = 0

    print("\n" + "="*60)
    print("🚀 STARTING TRAINING...")
    print("="*60 + "\n")

    for epoch in range(start_epoch, Config.epochs):
        # ---------- Training Phase ----------
        model.train()
        running_loss = 0.0
        correct = 0
        total = 0

        for batch_idx, (images, labels) in enumerate(train_loader):
            images, labels = images.to(device), labels.to(device)

            optimizer.zero_grad()

            if Config.use_amp and scaler:
                with autocast():
                    outputs = model(images)
                    loss = criterion(outputs, labels)

                scaler.scale(loss).backward()
                scaler.step(optimizer)
                scaler.update()
            else:
                outputs = model(images)
                loss = criterion(outputs, labels)
                loss.backward()
                optimizer.step()

            running_loss += loss.item()
            _, predicted = torch.max(outputs.data, 1)
            total += labels.size(0)
            correct += (predicted == labels).sum().item()

            if (batch_idx + 1) % 10 == 0:
                print(f'Epoch {epoch+1}/{Config.epochs}, Batch {batch_idx+1}/{len(train_loader)}, Loss: {loss.item():.4f}')

        train_loss = running_loss / len(train_loader)
        train_acc = 100 * correct / total
        train_losses.append(train_loss)
        train_accuracies.append(train_acc)

        # ---------- Validation Phase ----------
        model.eval()
        val_loss = 0.0
        correct = 0
        total = 0

        with torch.no_grad():
            for images, labels in val_loader:
                images, labels = images.to(device), labels.to(device)

                outputs = model(images)
                loss = criterion(outputs, labels)

                val_loss += loss.item()
                _, predicted = torch.max(outputs.data, 1)
                total += labels.size(0)
                correct += (predicted == labels).sum().item()

        val_loss = val_loss / len(val_loader)
        val_acc = 100 * correct / total
        val_losses.append(val_loss)
        val_accuracies.append(val_acc)

        # Update learning rate
        scheduler.step(val_loss)

        # Print epoch summary
        print(f"\n{'='*60}")
        print(f"Epoch {epoch+1}/{Config.epochs}")
        print(f"Train Loss: {train_loss:.4f} | Train Acc: {train_acc:.2f}%")
        print(f"Val Loss: {val_loss:.4f} | Val Acc: {val_acc:.2f}%")
        print(f"Learning Rate: {optimizer.param_groups[0]['lr']:.6f}")
        print(f"{'='*60}\n")

        # Save checkpoint after every epoch
        is_best = val_acc > best_val_acc
        if is_best:
            best_val_acc = val_acc
            early_stop_counter = 0
        else:
            early_stop_counter += 1

        save_checkpoint(
            epoch, model, optimizer, scheduler, scaler,
            train_losses, val_losses, train_accuracies, val_accuracies,
            best_val_acc, is_best
        )

        # Early stopping
        if early_stop_counter >= Config.patience:
            print(f"🛑 Early stopping triggered after {Config.patience} epochs without improvement.")
            break

    return train_losses, val_losses, train_accuracies, val_accuracies, best_val_acc

# ============================================
# 11. Train the Model
# ============================================
start_time = time.time()

train_losses, val_losses, train_accuracies, val_accuracies, best_val_acc = train_model(
    model, train_loader, val_loader, criterion, optimizer, scheduler, scaler
)

end_time = time.time()
training_time = end_time - start_time
print(f"\n✅ Training completed in {training_time:.2f} seconds ({training_time/60:.2f} minutes)")

# ============================================
# 12. Plot Training Curves
# ============================================
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 5))

ax1.plot(train_losses, label='Train Loss', color='blue', linewidth=2)
ax1.plot(val_losses, label='Val Loss', color='red', linewidth=2)
ax1.set_xlabel('Epoch')
ax1.set_ylabel('Loss')
ax1.set_title('Training and Validation Loss', fontsize=12)
ax1.legend()
ax1.grid(True)

ax2.plot(train_accuracies, label='Train Accuracy', color='blue', linewidth=2)
ax2.plot(val_accuracies, label='Val Accuracy', color='red', linewidth=2)
ax2.set_xlabel('Epoch')
ax2.set_ylabel('Accuracy (%)')
ax2.set_title('Training and Validation Accuracy', fontsize=12)
ax2.legend()
ax2.grid(True)

plt.tight_layout()
plt.savefig(os.path.join(Config.checkpoint_dir, 'training_curves.png'), dpi=300)
plt.show()

print(f"✅ Training curves saved to: {Config.checkpoint_dir}/training_curves.png")

# ============================================
# 13. Load Best Model for Testing
# ============================================
print("\n" + "="*60)
print("LOADING BEST MODEL FOR TESTING...")
print("="*60)

if os.path.exists(Config.best_model_path):
    checkpoint = torch.load(Config.best_model_path, map_location=device)
    model.load_state_dict(checkpoint['model_state_dict'])
    print(f"✅ Loaded best model from epoch {checkpoint['epoch']+1} with Val Acc: {checkpoint['best_val_acc']:.2f}%")
else:
    print("⚠️ Best model not found. Using current model.")

model.eval()

# ============================================
# 14. Evaluate on Test Set
# ============================================
print("\n" + "="*60)
print("TEST SET EVALUATION:")
print("="*60)

all_preds = []
all_labels = []

with torch.no_grad():
    for images, labels in test_loader:
        images = images.to(device)
        outputs = model(images)
        _, predicted = torch.max(outputs, 1)
        all_preds.extend(predicted.cpu().numpy())
        all_labels.extend(labels.cpu().numpy())

test_correct = sum(1 for p, l in zip(all_preds, all_labels) if p == l)
test_accuracy = 100 * test_correct / len(all_labels)

print(f"\n✅ Test Accuracy: {test_accuracy:.2f}%")

print("\nClassification Report:")
print(classification_report(all_labels, all_preds, target_names=class_names))

# Confusion Matrix
cm = confusion_matrix(all_labels, all_preds)

plt.figure(figsize=(10, 8))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=class_names,
            yticklabels=class_names)
plt.title('Confusion Matrix - MobileNetV3', fontsize=14)
plt.xlabel('Predicted', fontsize=12)
plt.ylabel('Actual', fontsize=12)
plt.tight_layout()
plt.savefig(os.path.join(Config.checkpoint_dir, 'confusion_matrix.png'), dpi=300)
plt.show()

# ============================================
# 15. Save Final Model
# ============================================
torch.save(model.state_dict(), Config.final_model_path)
torch.save(model, os.path.join(Config.checkpoint_dir, 'final_mobilenetv3_full.pth'))

print(f"\n✅ Models saved to: {Config.checkpoint_dir}")
print(f"   - mobilenetv3_checkpoint.pth (latest checkpoint)")
print(f"   - best_mobilenetv3.pth (best model)")
print(f"   - final_mobilenetv3.pth (final weights)")

# ============================================
# 16. Model Summary
# ============================================
print("\n" + "="*60)
print("MODEL SUMMARY:")
print("="*60)
print(f"Architecture: MobileNetV3 Large")
print(f"Input Shape: (3, {Config.input_size}, {Config.input_size})")
print(f"Output Classes: {num_classes}")
print(f"Class Names: {class_names}")
print(f"\nTraining Mode: From Scratch")
print(f"\nDataset Split:")
print(f"  - Training Samples: {len(train_dataset)}")
print(f"  - Validation Samples: {len(val_dataset)}")
print(f"  - Test Samples: {len(test_dataset)}")
print(f"\nTraining Configuration:")
print(f"  - Batch Size: {Config.batch_size}")
print(f"  - Learning Rate: {Config.learning_rate}")
print(f"  - Weight Decay: {Config.weight_decay}")
print(f"  - Optimizer: Adam")
print(f"  - Scheduler: ReduceLROnPlateau")
print(f"  - Mixed Precision: {Config.use_amp}")
print(f"\nResults:")
print(f"  - Best Validation Accuracy: {best_val_acc:.2f}%")
print(f"  - Test Accuracy: {test_accuracy:.2f}%")
print(f"  - Training Time: {training_time/60:.2f} minutes")
print("="*60)

print("\n" + "="*60)
print("🎉 TRAINING COMPLETE! 🎉")
print("="*60)
print("\n📁 All files saved to Google Drive:")
print(f"   📂 {Config.checkpoint_dir}/")
print("   ├── 📊 training_curves.png")
print("   ├── 📊 confusion_matrix.png")
print("   ├── 💾 mobilenetv3_checkpoint.pth (resumable checkpoint)")
print("   ├── 💾 best_mobilenetv3.pth (best model)")
print("   ├── 💾 final_mobilenetv3.pth (final weights)")
print("   ├── 💾 final_mobilenetv3_full.pth (full model)")
print("   └── 📄 training_metadata.json")
print("="*60)

"""**Extracting the information(logs) from the models which is trained and stored on the drive**"""

# ============================================
# Extract Training Information from Saved Checkpoint
# ============================================

import torch
import json
import os
import matplotlib.pyplot as plt
import numpy as np

# ============================================
# 1. Configuration - Update with your paths
# ============================================
class Config:
    # Path to your saved checkpoints (UPDATE THIS)
    checkpoint_dir = '/content/drive/MyDrive/checkpoints'  # Update with your path
    checkpoint_path = os.path.join(checkpoint_dir, 'mobilenetv3_checkpoint.pth')
    best_model_path = os.path.join(checkpoint_dir, 'best_mobilenetv3.pth')
    metadata_path = os.path.join(checkpoint_dir, 'training_metadata.json')

    # If using local VM instead of Google Drive, use:
    # checkpoint_dir = './checkpoints'

# ============================================
# 2. Load Checkpoint and Display Training Info
# ============================================
print("="*60)
print("📊 LOADING TRAINING INFORMATION FROM CHECKPOINT")
print("="*60)

# Check if checkpoint exists
if not os.path.exists(Config.checkpoint_path):
    print(f"❌ Checkpoint not found at: {Config.checkpoint_path}")
    print("\nSearching for checkpoints in common locations...")

    # Search for checkpoint files
    search_paths = [
        './checkpoints',
        '/content/drive/MyDrive/checkpoints',
        '/home/ds-khel/mobilenet/checkpoints',
    ]

    found = False
    for path in search_paths:
        if os.path.exists(path):
            checkpoint_file = os.path.join(path, 'mobilenetv3_checkpoint.pth')
            if os.path.exists(checkpoint_file):
                Config.checkpoint_path = checkpoint_file
                Config.checkpoint_dir = path
                Config.metadata_path = os.path.join(path, 'training_metadata.json')
                found = True
                print(f"✅ Found checkpoint at: {Config.checkpoint_path}")
                break

    if not found:
        print("❌ No checkpoint found. Please update the path.")
        exit(1)

# Load the checkpoint
checkpoint = torch.load(Config.checkpoint_path, map_location='cpu')

print("\n" + "="*60)
print("📊 TRAINING INFORMATION")
print("="*60)

# ============================================
# 3. Basic Information
# ============================================
print("\n📌 BASIC INFORMATION:")
print("-"*40)
print(f"Last completed epoch: {checkpoint['epoch'] + 1}")
print(f"Total classes: {checkpoint['num_classes']}")
print(f"Class names: {checkpoint['class_names']}")

if 'config' in checkpoint:
    print("\n📌 CONFIGURATION:")
    print("-"*40)
    config = checkpoint['config']
    for key, value in config.items():
        print(f"  {key}: {value}")

# ============================================
# 4. Training Metrics
# ============================================
print("\n📌 TRAINING METRICS:")
print("-"*40)

# Get training history
train_losses = checkpoint.get('train_losses', [])
val_losses = checkpoint.get('val_losses', [])
train_accuracies = checkpoint.get('train_accuracies', [])
val_accuracies = checkpoint.get('val_accuracies', [])
best_val_acc = checkpoint.get('best_val_acc', 0.0)

print(f"Best Validation Accuracy: {best_val_acc:.2f}%")

if train_losses:
    print(f"\n📈 Loss History:")
    print(f"  Initial Train Loss: {train_losses[0]:.4f}")
    print(f"  Final Train Loss: {train_losses[-1]:.4f}")
    print(f"  Best Train Loss: {min(train_losses):.4f}")

    print(f"\n  Initial Val Loss: {val_losses[0]:.4f}")
    print(f"  Final Val Loss: {val_losses[-1]:.4f}")
    print(f"  Best Val Loss: {min(val_losses):.4f}")

if train_accuracies:
    print(f"\n📈 Accuracy History:")
    print(f"  Initial Train Accuracy: {train_accuracies[0]:.2f}%")
    print(f"  Final Train Accuracy: {train_accuracies[-1]:.2f}%")
    print(f"  Best Train Accuracy: {max(train_accuracies):.2f}%")

    print(f"\n  Initial Val Accuracy: {val_accuracies[0]:.2f}%")
    print(f"  Final Val Accuracy: {val_accuracies[-1]:.2f}%")
    print(f"  Best Val Accuracy: {max(val_accuracies):.2f}%")

# ============================================
# 5. Best Model Information
# ============================================
if os.path.exists(Config.best_model_path):
    print("\n📌 BEST MODEL INFORMATION:")
    print("-"*40)
    best_checkpoint = torch.load(Config.best_model_path, map_location='cpu')
    print(f"Best model saved at epoch: {best_checkpoint['epoch'] + 1}")
    print(f"Best Validation Accuracy: {best_checkpoint['best_val_acc']:.2f}%")
    print(f"Class names: {best_checkpoint['class_names']}")

# ============================================
# 6. Metadata (if available)
# ============================================
if os.path.exists(Config.metadata_path):
    print("\n📌 METADATA:")
    print("-"*40)
    with open(Config.metadata_path, 'r') as f:
        metadata = json.load(f)
    for key, value in metadata.items():
        print(f"  {key}: {value}")

# ============================================
# 7. Plot Training Curves
# ============================================
if train_losses and val_losses:
    print("\n📌 PLOTTING TRAINING CURVES...")

    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 5))

    # Loss plot
    ax1.plot(train_losses, label='Train Loss', color='blue', linewidth=2)
    ax1.plot(val_losses, label='Val Loss', color='red', linewidth=2)
    ax1.axhline(y=min(val_losses), color='green', linestyle='--',
                label=f'Best Val Loss: {min(val_losses):.4f}')
    ax1.set_xlabel('Epoch')
    ax1.set_ylabel('Loss')
    ax1.set_title('Training and Validation Loss', fontsize=12)
    ax1.legend()
    ax1.grid(True)

    # Accuracy plot
    ax2.plot(train_accuracies, label='Train Accuracy', color='blue', linewidth=2)
    ax2.plot(val_accuracies, label='Val Accuracy', color='red', linewidth=2)
    ax2.axhline(y=max(val_accuracies), color='green', linestyle='--',
                label=f'Best Val Acc: {max(val_accuracies):.2f}%')
    ax2.set_xlabel('Epoch')
    ax2.set_ylabel('Accuracy (%)')
    ax2.set_title('Training and Validation Accuracy', fontsize=12)
    ax2.legend()
    ax2.grid(True)

    plt.tight_layout()
    plt.show()

    # Save the plot
    plot_path = os.path.join(Config.checkpoint_dir, 'extracted_training_curves.png')
    plt.savefig(plot_path, dpi=300)
    print(f"✅ Training curves saved to: {plot_path}")

# ============================================
# 8. Summary Statistics
# ============================================
print("\n" + "="*60)
print("📊 SUMMARY STATISTICS")
print("="*60)

if train_losses and val_losses and train_accuracies and val_accuracies:
    print(f"""
    ╔══════════════════════════════════════════════════════════╗
    ║                    TRAINING SUMMARY                      ║
    ╠══════════════════════════════════════════════════════════╣
    ║  Total Epochs          : {len(train_losses)}                             ║
    ║  Best Val Accuracy     : {max(val_accuracies):.2f}%                         ║
    ║  Best Train Accuracy   : {max(train_accuracies):.2f}%                         ║
    ║  Best Val Loss         : {min(val_losses):.4f}                           ║
    ║  Best Train Loss       : {min(train_losses):.4f}                           ║
    ║  Final Val Accuracy    : {val_accuracies[-1]:.2f}%                         ║
    ║  Final Train Accuracy  : {train_accuracies[-1]:.2f}%                         ║
    ║  Final Val Loss        : {val_losses[-1]:.4f}                           ║
    ║  Final Train Loss      : {train_losses[-1]:.4f}                           ║
    ╚══════════════════════════════════════════════════════════╝
    """)

# ============================================
# 9. Export to CSV (Optional)
# ============================================
def export_to_csv():
    """Export training history to CSV file."""
    if not train_losses:
        return

    import csv
    csv_path = os.path.join(Config.checkpoint_dir, 'training_history.csv')

    with open(csv_path, 'w', newline='') as f:
        writer = csv.writer(f)
        writer.writerow(['Epoch', 'Train Loss', 'Val Loss', 'Train Acc', 'Val Acc'])
        for i in range(len(train_losses)):
            writer.writerow([
                i + 1,
                train_losses[i],
                val_losses[i],
                train_accuracies[i],
                val_accuracies[i]
            ])

    print(f"✅ Training history exported to: {csv_path}")

# Uncomment to export
# export_to_csv()

print("\n" + "="*60)
print("✅ EXTRACTION COMPLETE!")
print("="*60)

"""Extracting the information from the model which is trained on the very minute imbalanced dataset"""

# ============================================
# Load Trained Model from Google Drive and Evaluate
# ============================================

import torch
import torch.nn as nn
from torchvision import datasets, transforms, models
from torch.utils.data import DataLoader
from sklearn.metrics import classification_report, confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
import os
from google.colab import drive
from PIL import Image
import warnings
warnings.filterwarnings('ignore')

# ============================================
# 1. Mount Google Drive
# ============================================
drive.mount('/content/drive')

# ============================================
# 2. Configuration
# ============================================
class Config:
    # Model path - UPDATE THIS TO YOUR MODEL PATH
    # For BEST MODEL:
    model_path = '/content/drive/MyDrive/checkpoints/best_mobilenetv3.pth'
    # For FINAL MODEL:
    # model_path = '/content/drive/MyDrive/checkpoints/final_mobilenetv3.pth'

    # Dataset path - UPDATE THIS
    data_dir = '/content/drive/MyDrive/Milestone2(AI LAB)/final_dataset (1)'

    # Model parameters
    input_size = 224
    num_classes = 5
    class_names = ['other_activities', 'safe_driving', 'talking_phone', 'texting_phone', 'turning']

    # Batch size for testing
    batch_size = 32
    num_workers = 2

# ============================================
# 3. Check for GPU
# ============================================
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

if device.type == 'cuda':
    print(f"GPU: {torch.cuda.get_device_name(0)}")
    print(f"GPU Memory: {torch.cuda.get_device_properties(0).total_memory / 1e9:.2f} GB")

# ============================================
# 4. Define Transforms
# ============================================
test_transform = transforms.Compose([
    transforms.Resize((Config.input_size, Config.input_size)),
    transforms.ToTensor(),
    transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
])

# ============================================
# 5. Load Dataset
# ============================================
print("\n" + "="*60)
print("LOADING DATASET...")
print("="*60)

test_dir = os.path.join(Config.data_dir, 'test')

if not os.path.exists(test_dir):
    print(f"❌ Test folder not found at: {test_dir}")
    # Try alternative path
    alt_path = '/content/drive/MyDrive/Driver_Activity_Dataset_20Percent/test'
    if os.path.exists(alt_path):
        test_dir = alt_path
        print(f"✅ Using alternative path: {test_dir}")
    else:
        exit(1)

test_dataset = datasets.ImageFolder(root=test_dir, transform=test_transform)
class_names = test_dataset.classes

print(f"\nTest samples: {len(test_dataset)}")
print(f"Class names: {class_names}")

# ============================================
# 6. Create DataLoader
# ============================================
test_loader = DataLoader(
    test_dataset,
    batch_size=Config.batch_size,
    shuffle=False,
    num_workers=Config.num_workers,
    pin_memory=True if torch.cuda.is_available() else False
)

print(f"✅ Test DataLoader created!")
print(f"   - Test batches: {len(test_loader)}")

# ============================================
# 7. Load Trained Model
# ============================================
print("\n" + "="*60)
print("LOADING TRAINED MODEL...")
print("="*60)

# Create model architecture
model = models.mobilenet_v3_large(weights=None)
model.classifier[3] = nn.Linear(in_features=1280, out_features=Config.num_classes)

# Load model
if os.path.exists(Config.model_path):
    checkpoint = torch.load(Config.model_path, map_location=device)

    # Check if it's a checkpoint dict or state dict
    if 'model_state_dict' in checkpoint:
        model.load_state_dict(checkpoint['model_state_dict'])
        print(f"✅ Loaded model from: {Config.model_path}")
        print(f"   - Epoch: {checkpoint.get('epoch', 'N/A')}")
        print(f"   - Best Validation Accuracy: {checkpoint.get('best_val_acc', 'N/A')}%")
    else:
        model.load_state_dict(checkpoint)
        print(f"✅ Loaded model from: {Config.model_path}")
else:
    print(f"❌ Model not found at: {Config.model_path}")
    exit(1)

model = model.to(device)
model.eval()
print("✅ Model ready for evaluation!")

# ============================================
# 8. Evaluate on Test Set
# ============================================
print("\n" + "="*60)
print("TEST SET EVALUATION:")
print("="*60)

all_preds = []
all_labels = []
all_probs = []

with torch.no_grad():
    for images, labels in test_loader:
        images = images.to(device)
        outputs = model(images)
        probs = torch.softmax(outputs, dim=1)
        _, predicted = torch.max(outputs, 1)
        all_preds.extend(predicted.cpu().numpy())
        all_labels.extend(labels.cpu().numpy())
        all_probs.extend(probs.cpu().numpy())

# Calculate test accuracy
test_correct = sum(1 for p, l in zip(all_preds, all_labels) if p == l)
test_accuracy = 100 * test_correct / len(all_labels)

print(f"\n✅ Test Accuracy: {test_accuracy:.2f}%")

# Classification Report
print("\nClassification Report:")
print(classification_report(all_labels, all_preds, target_names=class_names))

# ============================================
# 9. Confusion Matrix
# ============================================
cm = confusion_matrix(all_labels, all_preds)

plt.figure(figsize=(10, 8))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=class_names,
            yticklabels=class_names)
plt.title('Confusion Matrix - MobileNetV3', fontsize=14)
plt.xlabel('Predicted', fontsize=12)
plt.ylabel('Actual', fontsize=12)
plt.tight_layout()
plt.savefig('/content/drive/MyDrive/confusion_matrix_evaluation.png', dpi=300)
plt.show()

print(f"✅ Confusion matrix saved to: /content/drive/MyDrive/confusion_matrix_evaluation.png")

# ============================================
# 10. Per-Class Accuracy
# ============================================
print("\n" + "="*60)
print("PER-CLASS ACCURACY:")
print("="*60)

class_correct = [0] * Config.num_classes
class_total = [0] * Config.num_classes

for pred, label in zip(all_preds, all_labels):
    if pred == label:
        class_correct[label] += 1
    class_total[label] += 1

for idx, class_name in enumerate(class_names):
    if class_total[idx] > 0:
        acc = 100 * class_correct[idx] / class_total[idx]
        print(f"  {class_name:20s}: {acc:.2f}% ({class_correct[idx]}/{class_total[idx]})")

# ============================================
# 11. Detailed Results
# ============================================
print("\n" + "="*60)
print("DETAILED RESULTS:")
print("="*60)

# Get predictions with probabilities
print("\n📊 Sample Predictions:")
print("-"*60)
num_samples = min(10, len(test_dataset))

for i in range(num_samples):
    img_path, true_label = test_dataset.imgs[i]
    true_class = class_names[true_label]

    # Get prediction for this image
    image = Image.open(img_path).convert('RGB')
    input_tensor = test_transform(image).unsqueeze(0).to(device)

    with torch.no_grad():
        outputs = model(input_tensor)
        probs = torch.softmax(outputs, dim=1)
        confidence, predicted = torch.max(probs, 1)

    pred_class = class_names[predicted.item()]
    conf = confidence.item() * 100

    status = "✅" if pred_class == true_class else "❌"
    print(f"  {status} {os.path.basename(img_path):30s} | True: {true_class:15s} | Pred: {pred_class:15s} | Conf: {conf:.2f}%")

# ============================================
# 12. Save Results to File
# ============================================
results_path = '/content/drive/MyDrive/evaluation_results.txt'

with open(results_path, 'w') as f:
    f.write("="*60 + "\n")
    f.write("MODEL EVALUATION RESULTS\n")
    f.write("="*60 + "\n\n")
    f.write(f"Model Path: {Config.model_path}\n")
    f.write(f"Test Accuracy: {test_accuracy:.2f}%\n\n")

    f.write("Classification Report:\n")
    f.write(classification_report(all_labels, all_preds, target_names=class_names))
    f.write("\n" + "="*60 + "\n")

    f.write("Per-Class Accuracy:\n")
    for idx, class_name in enumerate(class_names):
        if class_total[idx] > 0:
            acc = 100 * class_correct[idx] / class_total[idx]
            f.write(f"  {class_name:20s}: {acc:.2f}% ({class_correct[idx]}/{class_total[idx]})\n")

    f.write("\nConfusion Matrix:\n")
    f.write(str(cm))

print(f"✅ Results saved to: {results_path}")

# ============================================
# 13. Summary
# ============================================
print("\n" + "="*60)
print("EVALUATION SUMMARY:")
print("="*60)
print(f"Architecture: MobileNetV3 Large")
print(f"Test Accuracy: {test_accuracy:.2f}%")
print(f"Total Test Samples: {len(test_dataset)}")
print(f"Number of Classes: {Config.num_classes}")
print(f"Class Names: {class_names}")
print("="*60)
print("\n🎉 Evaluation Complete!")

from google.colab import drive
drive.mount('/content/drive')

"""Extracting the dataset information"""

# ==========================================================
# Dataset Statistics (Train / Val / Test)
# ==========================================================

import os
from google.colab import drive

# ----------------------------------------------------------
# 1. Mount Google Drive
# ----------------------------------------------------------
drive.mount('/content/drive')

# ----------------------------------------------------------
# 2. Enter Dataset Path
# Example:
# /content/drive/MyDrive/Driver_Activity_Dataset
# ----------------------------------------------------------
DATASET_PATH = "/content/drive/MyDrive/Milestone2(AI LAB)/final_dataset"

# ----------------------------------------------------------
# 3. Image Extensions
# ----------------------------------------------------------
IMAGE_EXTENSIONS = (
    ".jpg", ".jpeg", ".png",
    ".bmp", ".tif", ".tiff",
    ".webp"
)

# ----------------------------------------------------------
# 4. Function to Count Images
# ----------------------------------------------------------
def count_images(folder):

    class_counts = {}
    total = 0

    if not os.path.exists(folder):
        print(f"❌ Folder not found: {folder}")
        return class_counts, total

    for class_name in sorted(os.listdir(folder)):

        class_path = os.path.join(folder, class_name)

        if not os.path.isdir(class_path):
            continue

        count = sum(
            1
            for file in os.listdir(class_path)
            if file.lower().endswith(IMAGE_EXTENSIONS)
        )

        class_counts[class_name] = count
        total += count

    return class_counts, total

# ----------------------------------------------------------
# 5. Count Images
# ----------------------------------------------------------
splits = ["train", "val", "test"]

overall_total = 0

print("="*70)
print("DATASET SUMMARY")
print("="*70)

for split in splits:

    split_path = os.path.join(DATASET_PATH, split)

    class_counts, total = count_images(split_path)

    overall_total += total

    print(f"\n{split.upper()}")

    print("-"*70)

    for cls, cnt in class_counts.items():
        print(f"{cls:<25} {cnt}")

    print("-"*70)
    print(f"Total {split}: {total}")

print("\n" + "="*70)
print(f"TOTAL IMAGES IN DATASET : {overall_total}")
print("="*70)

"""**Testing Models on the Images**"""

# ============================================
# MobileNetV3 Model Testing on Single Images
# Trained Model: Driver Activity Classification
# ============================================

import torch
import torch.nn as nn
from torchvision import transforms, models
from PIL import Image
import matplotlib.pyplot as plt
import numpy as np
import os
from google.colab import drive
from IPython.display import display, Image as IPImage
import warnings
warnings.filterwarnings('ignore')

# ============================================
# 1. Mount Google Drive
# ============================================
drive.mount('/content/drive')

# ============================================
# 2. Configuration
# ============================================
class Config:
    checkpoint_dir = '/content/drive/MyDrive/checkpoints'
    best_model_path = os.path.join(checkpoint_dir, 'best_mobilenetv3.pth')
    final_model_path = os.path.join(checkpoint_dir, 'final_mobilenetv3.pth')

    input_size = 224
    num_classes = 5
    class_names = ['other_activities', 'safe_driving', 'talking_phone', 'texting_phone', 'turning']

# ============================================
# 3. Check for GPU
# ============================================
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

# ============================================
# 4. Define Transforms (Same as Validation)
# ============================================
test_transform = transforms.Compose([
    transforms.Resize((Config.input_size, Config.input_size)),
    transforms.ToTensor(),
    transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
])

# ============================================
# 5. Load the Trained Model (BEST MODEL) - FIXED
# ============================================
print("\n" + "="*60)
print("LOADING TRAINED MODEL...")
print("="*60)

# Create model architecture
model = models.mobilenet_v3_large(weights=None)
model.classifier[3] = nn.Linear(in_features=1280, out_features=Config.num_classes)

# Load best model - FIXED: Extract model_state_dict from checkpoint
if os.path.exists(Config.best_model_path):
    checkpoint = torch.load(Config.best_model_path, map_location=device)

    # Check if it's a checkpoint dict or state dict
    if 'model_state_dict' in checkpoint:
        # It's a checkpoint with multiple keys
        model.load_state_dict(checkpoint['model_state_dict'])
        print(f"✅ Loaded BEST MODEL from: {Config.best_model_path}")
        print(f"   - Epoch: {checkpoint.get('epoch', 'N/A')}")
        print(f"   - Best Validation Accuracy: {checkpoint.get('best_val_acc', 'N/A')}%")
    else:
        # It's a direct state dict
        model.load_state_dict(checkpoint)
        print(f"✅ Loaded BEST MODEL from: {Config.best_model_path}")
else:
    print(f"❌ Best model not found. Trying final model...")
    if os.path.exists(Config.final_model_path):
        checkpoint = torch.load(Config.final_model_path, map_location=device)
        if 'model_state_dict' in checkpoint:
            model.load_state_dict(checkpoint['model_state_dict'])
        else:
            model.load_state_dict(checkpoint)
        print(f"✅ Loaded FINAL MODEL from: {Config.final_model_path}")

model = model.to(device)
model.eval()
print("✅ Model is ready for inference")
print("="*60 + "\n")

# ============================================
# 6. Single Image Prediction Function
# ============================================
def predict_image(image_path, model, transform, class_names, show_plot=True):
    """
    Predict the class of a single image and display results.

    Args:
        image_path: Path to the image
        model: Trained model
        transform: Image transforms
        class_names: List of class names
        show_plot: Whether to display the plot

    Returns:
        Dictionary with prediction results
    """
    if not os.path.exists(image_path):
        print(f"❌ Image not found: {image_path}")
        return None

    # Load and preprocess image
    image = Image.open(image_path).convert('RGB')
    original_image = image.copy()

    # Apply transforms
    image_tensor = transform(image).unsqueeze(0).to(device)

    # Make prediction
    with torch.no_grad():
        outputs = model(image_tensor)
        probabilities = torch.softmax(outputs, dim=1)
        _, predicted = torch.max(outputs, 1)

    # Get results
    predicted_class = class_names[predicted.item()]
    confidence = probabilities[0][predicted.item()].item() * 100
    all_probs = probabilities[0].cpu().numpy()

    result = {
        'predicted_class': predicted_class,
        'confidence': confidence,
        'all_probabilities': all_probs,
        'original_image': original_image,
        'predicted_index': predicted.item(),
        'image_path': image_path
    }

    # Display results
    if show_plot:
        display_prediction(result, class_names)

    return result

# ============================================
# 7. Display Prediction Results in Colab
# ============================================
def display_prediction(result, class_names):
    """
    Display the image with prediction results in Colab.
    """
    if result is None:
        return

    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 5))

    # Left: Image with prediction
    ax1.imshow(np.array(result['original_image']))

    # Set title with prediction and confidence
    title = f"Prediction: {result['predicted_class']}\nConfidence: {result['confidence']:.2f}%"
    ax1.set_title(title, fontsize=14, fontweight='bold', color='green')
    ax1.axis('off')

    # Right: Probability bar chart
    colors = ['red' if i == result['predicted_index'] else 'steelblue'
              for i in range(len(class_names))]
    bars = ax2.bar(class_names, result['all_probabilities'] * 100, color=colors)
    ax2.set_ylabel('Probability (%)', fontsize=12)
    ax2.set_title('Class Probabilities', fontsize=14)
    ax2.set_ylim(0, 100)
    ax2.set_xticklabels(class_names, rotation=45, ha='right')

    # Add value labels on bars
    for bar, prob in zip(bars, result['all_probabilities'] * 100):
        height = bar.get_height()
        ax2.text(bar.get_x() + bar.get_width()/2., height + 1,
                f'{prob:.1f}%', ha='center', va='bottom', fontsize=9)

    plt.tight_layout()

    # Show the plot in Colab
    plt.show()

    # Print results in terminal
    print("\n" + "="*60)
    print("📊 PREDICTION DETAILS:")
    print("="*60)
    print(f"📁 Image: {os.path.basename(result['image_path'])}")
    print(f"🎯 Predicted Class: {result['predicted_class']}")
    print(f"📈 Confidence: {result['confidence']:.2f}%")
    print("\n📋 All Class Probabilities:")
    print("-"*40)
    for idx, (name, prob) in enumerate(zip(class_names, result['all_probabilities'])):
        bar = "█" * int(prob * 50)
        print(f"  {name:20s}: {prob*100:6.2f}% {bar}")

# ============================================
# 8. Test a Single Image (Main Function)
# ============================================
def test_single_image(image_path):
    """
    Quick function to test a single image.
    """
    result = predict_image(image_path, model, test_transform, Config.class_names, show_plot=True)
    return result

# ============================================
# 9. Test Multiple Images from a Folder
# ============================================
def test_multiple_images(image_folder, output_folder=None):
    """
    Test all images in a folder.
    """
    if not os.path.exists(image_folder):
        print(f"❌ Folder not found: {image_folder}")
        return

    if output_folder:
        os.makedirs(output_folder, exist_ok=True)

    # Get all image files
    image_extensions = ['.jpg', '.jpeg', '.png', '.bmp', '.tiff']
    image_files = [f for f in os.listdir(image_folder)
                   if any(f.lower().endswith(ext) for ext in image_extensions)]

    if not image_files:
        print(f"No image files found in: {image_folder}")
        return

    print(f"\n🔍 Testing {len(image_files)} images...")
    print("="*60)

    results = []

    for img_file in image_files:
        img_path = os.path.join(image_folder, img_file)
        result = predict_image(img_path, model, test_transform, Config.class_names, show_plot=False)

        if result:
            results.append({
                'image_name': img_file,
                'predicted_class': result['predicted_class'],
                'confidence': result['confidence']
            })

    # Print summary
    print("\n" + "="*60)
    print("📊 BATCH TEST SUMMARY:")
    print("="*60)
    for r in results:
        print(f"  {r['image_name']:30s} → {r['predicted_class']:20s} ({r['confidence']:.2f}%)")

    return results

# ============================================
# 10. Save Result Image to Drive
# ============================================
def save_prediction_image(result, save_path):
    """
    Save the prediction result as an image.
    """
    if result is None:
        return

    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 5))

    # Left: Image with prediction
    ax1.imshow(np.array(result['original_image']))
    title = f"Prediction: {result['predicted_class']}\nConfidence: {result['confidence']:.2f}%"
    ax1.set_title(title, fontsize=14, fontweight='bold', color='green')
    ax1.axis('off')

    # Right: Probability bar chart
    colors = ['red' if i == result['predicted_index'] else 'steelblue'
              for i in range(len(Config.class_names))]
    bars = ax2.bar(Config.class_names, result['all_probabilities'] * 100, color=colors)
    ax2.set_ylabel('Probability (%)', fontsize=12)
    ax2.set_title('Class Probabilities', fontsize=14)
    ax2.set_ylim(0, 100)
    ax2.set_xticklabels(Config.class_names, rotation=45, ha='right')

    for bar, prob in zip(bars, result['all_probabilities'] * 100):
        height = bar.get_height()
        ax2.text(bar.get_x() + bar.get_width()/2., height + 1,
                f'{prob:.1f}%', ha='center', va='bottom', fontsize=9)

    plt.tight_layout()

    # Save
    plt.savefig(save_path, dpi=300, bbox_inches='tight')
    print(f"✅ Prediction saved to: {save_path}")
    plt.close()

# ============================================
# 11. TEST YOUR IMAGE HERE
# ============================================
print("\n" + "="*60)
print("📌 TEST YOUR IMAGE:")
print("="*60)
print("To test an image, use:")
print("  test_single_image('/path/to/your/image.jpg')")
print("="*60)

# ============================================
# EXAMPLE: Test a Single Image
# ============================================
# UPDATE THIS PATH WITH YOUR IMAGE
test_image_path = '/content/drive/MyDrive/Milestone2(AI LAB)/final_dataset (1)/train/safe_driving/2019-04-2416-18-11.png'  # ← Change this!

print("\n" + "="*60)
print("🔍 TESTING IMAGE...")
print("="*60)

# Check if it's a folder or file
if os.path.isdir(test_image_path):
    # It's a folder - list all images and test each
    print(f"📂 Folder detected. Testing all images in: {test_image_path}")
    test_multiple_images(test_image_path)
else:
    # It's a single file
    if os.path.exists(test_image_path):
        result = test_single_image(test_image_path)

        # Save the result
        if result:
            save_path = '/content/drive/MyDrive/prediction_result.png'
            save_prediction_image(result, save_path)
            display(IPImage(save_path))
    else:
        print(f"❌ Image not found: {test_image_path}")
        print("Please update the 'test_image_path' variable with your image path.")

"""**Testing trained model on the Input videos and save the output videos**"""

# ============================================
# MobileNetV3 Model Testing on Videos
# Trained Model: Driver Activity Classification
# ============================================

import torch
import torch.nn as nn
from torchvision import models, transforms
from PIL import Image, ImageDraw, ImageFont
import cv2
import numpy as np
import os
import time
from google.colab import drive
import matplotlib.pyplot as plt
from IPython.display import Video, display
import warnings
warnings.filterwarnings('ignore')

# ============================================
# 1. Mount Google Drive
# ============================================
drive.mount('/content/drive')

# ============================================
# 2. Configuration
# ============================================
class Config:
    # Model paths - Using FINAL MODEL
    checkpoint_dir = '/content/drive/MyDrive/checkpoints'
    model_path = os.path.join(checkpoint_dir, 'final_mobilenetv3.pth')  # Final model
    # model_path = os.path.join(checkpoint_dir, 'best_mobilenetv3.pth')  # For best model

    # Video paths
    input_video = '/content/1008770258-preview.mp4'  # Change this
    output_video = '/content/prediction_output_video.mp4'

    # Model parameters
    input_size = 224
    num_classes = 5
    class_names = ['other_activities', 'safe_driving', 'talking_phone', 'texting_phone', 'turning']

    # Video processing parameters
    frame_skip = 5  # Process every 5th frame (increase for faster processing)
    confidence_threshold = 0.5  # Minimum confidence to display prediction

# ============================================
# 3. Load Model
# ============================================
def load_model(model_path, num_classes):
    """
    Load the trained MobileNetV3 model.
    """
    print("\n" + "="*60)
    print("LOADING MODEL...")
    print("="*60)

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"Using device: {device}")

    # Create model architecture
    model = models.mobilenet_v3_large(weights=None)
    model.classifier[3] = nn.Linear(in_features=1280, out_features=num_classes)

    # Load model
    if os.path.exists(model_path):
        checkpoint = torch.load(model_path, map_location=device)
        if 'model_state_dict' in checkpoint:
            model.load_state_dict(checkpoint['model_state_dict'])
            print(f"✅ Loaded model from: {model_path}")
            print(f"   - Epoch: {checkpoint.get('epoch', 'N/A')}")
            print(f"   - Best Validation Accuracy: {checkpoint.get('best_val_acc', 'N/A')}%")
        else:
            model.load_state_dict(checkpoint)
            print(f"✅ Loaded model from: {model_path}")
    else:
        print(f"❌ Model not found at: {model_path}")
        return None, None

    model = model.to(device)
    model.eval()

    print("✅ Model ready for inference!")
    print("="*60 + "\n")

    return model, device

# ============================================
# 4. Transform for Input Image
# ============================================
def get_transform(input_size):
    """
    Get the image transform pipeline.
    """
    return transforms.Compose([
        transforms.Resize((input_size, input_size)),
        transforms.ToTensor(),
        transforms.Normalize(
            mean=[0.485, 0.456, 0.406],
            std=[0.229, 0.224, 0.225]
        )
    ])

# ============================================
# 5. Predict Single Frame
# ============================================
def predict_frame(frame, model, transform, device, class_names):
    """
    Predict the class of a single video frame.
    """
    # Convert frame to PIL image
    frame_rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
    pil_image = Image.fromarray(frame_rgb)

    # Transform image
    input_tensor = transform(pil_image).unsqueeze(0).to(device)

    # Make prediction
    with torch.no_grad():
        outputs = model(input_tensor)
        probabilities = torch.softmax(outputs, dim=1)
        confidence, predicted = torch.max(probabilities, 1)

    predicted_class = class_names[predicted.item()]
    confidence_score = confidence.item() * 100
    all_probs = probabilities[0].cpu().numpy()

    return {
        'class': predicted_class,
        'confidence': confidence_score,
        'probabilities': all_probs,
        'predicted_index': predicted.item()
    }

# ============================================
# 6. Process Video
# ============================================
def process_video(input_video_path, output_video_path, model, device,
                  class_names, transform, frame_skip=5, confidence_threshold=0.5):
    """
    Process video and add predictions to frames.
    """
    # Check if input video exists
    if not os.path.exists(input_video_path):
        print(f"❌ Video not found: {input_video_path}")
        return None

    # Open video
    cap = cv2.VideoCapture(input_video_path)

    # Get video properties
    fps = int(cap.get(cv2.CAP_PROP_FPS))
    width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
    height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
    total_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))

    print(f"\n📹 Video Information:")
    print(f"   - FPS: {fps}")
    print(f"   - Resolution: {width}x{height}")
    print(f"   - Total Frames: {total_frames}")
    print(f"   - Frame Skip: {frame_skip}")

    # Create video writer
    fourcc = cv2.VideoWriter_fourcc(*'mp4v')
    out = cv2.VideoWriter(output_video_path, fourcc, fps, (width, height))

    # Process frames
    frame_count = 0
    processed_count = 0
    predictions = []
    start_time = time.time()

    print(f"\n🔍 Processing video...")

    while True:
        ret, frame = cap.read()
        if not ret:
            break

        # Skip frames
        if frame_count % frame_skip == 0:
            # Get prediction
            result = predict_frame(frame, model, transform, device, class_names)
            predictions.append(result)

            # Draw prediction on frame
            frame_with_pred = draw_prediction(frame, result, class_names, confidence_threshold)
            out.write(frame_with_pred)

            processed_count += 1

            # Progress update
            if processed_count % 50 == 0:
                print(f"   Processed: {processed_count} frames")

        frame_count += 1

    # Release resources
    cap.release()
    out.release()

    end_time = time.time()
    processing_time = end_time - start_time

    print(f"\n✅ Video processing complete!")
    print(f"   - Total frames processed: {processed_count}")
    print(f"   - Processing time: {processing_time:.2f} seconds")
    print(f"   - Average FPS: {processed_count / processing_time:.2f}")
    print(f"   - Output saved to: {output_video_path}")

    return predictions

# ============================================
# 7. Draw Prediction on Frame
# ============================================
def draw_prediction(frame, result, class_names, confidence_threshold=0.5):
    """
    Draw prediction on video frame.
    """
    frame_copy = frame.copy()
    height, width = frame_copy.shape[:2]

    # Get prediction
    predicted_class = result['class']
    confidence = result['confidence']

    # Set color based on confidence
    if confidence > 80:
        color = (0, 255, 0)  # Green - High confidence
    elif confidence > 60:
        color = (0, 255, 255)  # Yellow - Medium confidence
    else:
        color = (0, 0, 255)  # Red - Low confidence

    # Draw background rectangle
    text = f"{predicted_class}: {confidence:.1f}%"
    (text_width, text_height), baseline = cv2.getTextSize(
        text, cv2.FONT_HERSHEY_SIMPLEX, 0.8, 2
    )

    cv2.rectangle(
        frame_copy,
        (10, 10),
        (10 + text_width + 20, 10 + text_height + 20),
        (0, 0, 0),
        -1
    )

    # Draw prediction text
    cv2.putText(
        frame_copy,
        text,
        (20, 10 + text_height + 10),
        cv2.FONT_HERSHEY_SIMPLEX,
        0.8,
        color,
        2,
        cv2.LINE_AA
    )

    # Draw class probabilities bar (optional)
    bar_x = 20
    bar_y = 10 + text_height + 30
    bar_width = 200
    bar_height = 15

    # Draw all class probabilities as small bars
    for i, (name, prob) in enumerate(zip(class_names, result['probabilities'])):
        prob_percent = prob * 100
        bar_color = (0, 255, 0) if i == result['predicted_index'] else (100, 100, 100)

        # Only show if probability > 5%
        if prob_percent > 5:
            cv2.rectangle(
                frame_copy,
                (bar_x, bar_y + i * 20),
                (bar_x + int(bar_width * (prob_percent / 100)), bar_y + i * 20 + 10),
                bar_color,
                -1
            )

    return frame_copy

# ============================================
# 8. Process Video with Timestamp
# ============================================
def process_video_with_timestamp(input_video_path, output_video_path, model, device,
                                  class_names, transform, frame_skip=5):
    """
    Process video and add predictions with timestamp.
    """
    if not os.path.exists(input_video_path):
        print(f"❌ Video not found: {input_video_path}")
        return None

    cap = cv2.VideoCapture(input_video_path)

    fps = int(cap.get(cv2.CAP_PROP_FPS))
    width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
    height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
    total_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))

    print(f"\n📹 Video Information:")
    print(f"   - FPS: {fps}")
    print(f"   - Resolution: {width}x{height}")
    print(f"   - Total Frames: {total_frames}")

    fourcc = cv2.VideoWriter_fourcc(*'mp4v')
    out = cv2.VideoWriter(output_video_path, fourcc, fps, (width, height))

    frame_count = 0
    processed_count = 0
    start_time = time.time()

    print(f"\n🔍 Processing video with timestamp...")

    while True:
        ret, frame = cap.read()
        if not ret:
            break

        if frame_count % frame_skip == 0:
            result = predict_frame(frame, model, transform, device, class_names)

            # Draw prediction with timestamp
            frame_copy = draw_prediction_with_timestamp(frame, result, class_names, frame_count, fps)
            out.write(frame_copy)

            processed_count += 1

            if processed_count % 50 == 0:
                print(f"   Processed: {processed_count} frames")

        frame_count += 1

    cap.release()
    out.release()

    end_time = time.time()
    processing_time = end_time - start_time

    print(f"\n✅ Video processing complete!")
    print(f"   - Total frames processed: {processed_count}")
    print(f"   - Processing time: {processing_time:.2f} seconds")
    print(f"   - Output saved to: {output_video_path}")

    return True

# ============================================
# 9. Draw Prediction with Timestamp
# ============================================
def draw_prediction_with_timestamp(frame, result, class_names, frame_count, fps):
    """
    Draw prediction with timestamp on frame.
    """
    frame_copy = frame.copy()
    height, width = frame_copy.shape[:2]

    predicted_class = result['class']
    confidence = result['confidence']

    # Get timestamp
    seconds = frame_count / fps
    minutes = int(seconds // 60)
    seconds = int(seconds % 60)
    timestamp = f"{minutes:02d}:{seconds:02d}"

    # Set color based on confidence
    if confidence > 80:
        color = (0, 255, 0)
    elif confidence > 60:
        color = (0, 255, 255)
    else:
        color = (0, 0, 255)

    # Draw prediction text
    text = f"{predicted_class}: {confidence:.1f}%"
    cv2.rectangle(frame_copy, (10, 10), (400, 80), (0, 0, 0), -1)
    cv2.putText(frame_copy, text, (20, 40), cv2.FONT_HERSHEY_SIMPLEX, 0.8, color, 2, cv2.LINE_AA)
    cv2.putText(frame_copy, f"Time: {timestamp}", (20, 70), cv2.FONT_HERSHEY_SIMPLEX, 0.6, (255, 255, 255), 1, cv2.LINE_AA)

    # Draw probability bars on the right side
    bar_x = width - 250
    bar_y = 50
    bar_width = 200
    bar_height = 20

    for i, (name, prob) in enumerate(zip(class_names, result['probabilities'])):
        prob_percent = prob * 100
        bar_color = (0, 255, 0) if i == result['predicted_index'] else (80, 80, 80)

        if prob_percent > 3:
            cv2.rectangle(
                frame_copy,
                (bar_x, bar_y + i * 30),
                (bar_x + int(bar_width * (prob_percent / 100)), bar_y + i * 30 + 15),
                bar_color,
                -1
            )
            cv2.putText(
                frame_copy,
                f"{name[:3]}: {prob_percent:.1f}%",
                (bar_x + 5, bar_y + i * 30 + 12),
                cv2.FONT_HERSHEY_SIMPLEX,
                0.4,
                (255, 255, 255),
                1,
                cv2.LINE_AA
            )

    return frame_copy

# ============================================
# 10. Real-Time Webcam Prediction (Optional)
# ============================================
def real_time_prediction(model, device, class_names, transform):
    """
    Real-time prediction from webcam.
    """
    print("\n🎥 Starting real-time webcam prediction...")
    print("   Press 'q' to quit")

    cap = cv2.VideoCapture(0)

    if not cap.isOpened():
        print("❌ Could not open webcam")
        return

    while True:
        ret, frame = cap.read()
        if not ret:
            break

        # Predict frame
        result = predict_frame(frame, model, transform, device, class_names)

        # Draw prediction
        frame = draw_prediction(frame, result, class_names)

        # Display
        cv2.imshow('Driver Activity Recognition', frame)

        if cv2.waitKey(1) & 0xFF == ord('q'):
            break

    cap.release()
    cv2.destroyAllWindows()

# ============================================
# 11. Main Execution
# ============================================
def main():
    # Load model
    model, device = load_model(Config.model_path, Config.num_classes)
    if model is None:
        return

    # Get transform
    transform = get_transform(Config.input_size)

    # Process video
    print("\n" + "="*60)
    print("📹 VIDEO PREDICTION")
    print("="*60)

    # Option 1: Process video with predictions
    predictions = process_video(
        input_video_path=Config.input_video,
        output_video_path=Config.output_video,
        model=model,
        device=device,
        class_names=Config.class_names,
        transform=transform,
        frame_skip=Config.frame_skip,
        confidence_threshold=Config.confidence_threshold
    )

    # Option 2: Process video with timestamp (uncomment to use)
    # process_video_with_timestamp(
    #     input_video_path=Config.input_video,
    #     output_video_path=Config.output_video,
    #     model=model,
    #     device=device,
    #     class_names=Config.class_names,
    #     transform=transform,
    #     frame_skip=Config.frame_skip
    # )

    # Display video in Colab
    if os.path.exists(Config.output_video):
        print("\n🎬 Playing output video...")
        display(Video(Config.output_video, embed=True, width=640))

    # Uncomment for real-time webcam prediction
    # real_time_prediction(model, device, Config.class_names, transform)

# ============================================
# 12. Run the Code
# ============================================
if __name__ == "__main__":
    main()

"""**Testing trained models on the videos frame by frame**"""

# ============================================
# MobileNetV3 - Frame by Frame Video Prediction
# No Frame Skipping
# ============================================

import torch
import torch.nn as nn
from torchvision import models, transforms
import cv2
import numpy as np
from PIL import Image
from google.colab import drive

# ============================================
# 1. Mount Drive & Setup
# ============================================
drive.mount('/content/drive')

# ============================================
# 2. Load Model
# ============================================
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

# Load model
model_path = '/content/drive/MyDrive/checkpoints/best_mobilenetv3.pth'
model = models.mobilenet_v3_large(weights=None)
model.classifier[3] = nn.Linear(1280, 5)

checkpoint = torch.load(model_path, map_location=device)
if 'model_state_dict' in checkpoint:
    model.load_state_dict(checkpoint['model_state_dict'])
else:
    model.load_state_dict(checkpoint)

model = model.to(device)
model.eval()
print("✅ Model loaded!")

# ============================================
# 3. Class Names & Transform
# ============================================
class_names = ['other_activities', 'safe_driving', 'talking_phone', 'texting_phone', 'turning']

transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
])

# ============================================
# 4. Process Video Frame by Frame
# ============================================
# Input/Output paths
input_video = '/content/1008770258-preview.mp4'  # Change this
output_video = '/content/output_no_skip.mp4'

# Open video
cap = cv2.VideoCapture(input_video)
fps = int(cap.get(cv2.CAP_PROP_FPS))
width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
total_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))

print(f"📹 Video: {fps}fps, {width}x{height}, {total_frames} frames")

# Create output video writer
fourcc = cv2.VideoWriter_fourcc(*'mp4v')
out = cv2.VideoWriter(output_video, fourcc, fps, (width, height))

frame_count = 0
print("\n🔍 Processing every frame...")

while True:
    ret, frame = cap.read()
    if not ret:
        break

    # --- PREDICT ON EVERY FRAME (NO SKIP) ---
    # Convert frame to PIL image
    frame_rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
    pil_image = Image.fromarray(frame_rgb)

    # Transform and predict
    input_tensor = transform(pil_image).unsqueeze(0).to(device)

    with torch.no_grad():
        outputs = model(input_tensor)
        probs = torch.softmax(outputs, dim=1)
        confidence, predicted = torch.max(probs, 1)

    pred_class = class_names[predicted.item()]
    conf = confidence.item() * 100

    # --- DRAW ON FRAME ---
    text = f"{pred_class}: {conf:.1f}%"

    # Background rectangle
    cv2.rectangle(frame, (10, 10), (400, 50), (0, 0, 0), -1)

    # Prediction text
    cv2.putText(frame, text, (20, 40), cv2.FONT_HERSHEY_SIMPLEX,
                0.8, (0, 255, 0), 2, cv2.LINE_AA)

    # --- WRITE FRAME ---
    out.write(frame)

    frame_count += 1

    # Progress update
    if frame_count % 100 == 0:
        print(f"   Processed: {frame_count}/{total_frames} frames")

# Release resources
cap.release()
out.release()

print(f"\n✅ Complete! Processed {frame_count} frames")
print(f"✅ Output saved to: {output_video}")

# ============================================
# 5. Display Output Video in Colab
# ============================================
from IPython.display import Video, display
display(Video(output_video, embed=True, width=640))

!pip install grad-cam

"""**Testing model using GradCam like which are it focuses during training**"""

import torch
import cv2
import numpy as np
import matplotlib.pyplot as plt

from PIL import Image

from pytorch_grad_cam import GradCAM
from pytorch_grad_cam.utils.image import show_cam_on_image
from pytorch_grad_cam.utils.model_targets import ClassifierOutputTarget
from torchvision import models
# Select device
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Using device:", device)

model = models.mobilenet_v3_large(weights=None)

model.classifier[3] = torch.nn.Linear(
    1280,
    5
)

checkpoint = torch.load(
    "/content/drive/MyDrive/checkpoints/best_mobilenetv3.pth",
    map_location=device
)

model.load_state_dict(
    checkpoint["model_state_dict"]
)

model.to(device)
model.eval()

target_layers = [model.features[-1]]
from torchvision import transforms

transform = transforms.Compose([
    transforms.Resize((224,224)),
    transforms.ToTensor(),
    transforms.Normalize(
        [0.485,0.456,0.406],
        [0.229,0.224,0.225]
    )
])

image = Image.open("/content/drive/MyDrive/Milestone2(AI LAB)/final_dataset/train/safe_driving/2019-04-2416-18-23.png").convert("RGB")

input_tensor = transform(image).unsqueeze(0).to(device)

with torch.no_grad():

    output = model(input_tensor)

prediction = output.argmax(dim=1).item()

print(prediction)

cam = GradCAM(
    model=model,
    target_layers=target_layers
)

targets = [ClassifierOutputTarget(prediction)]

grayscale_cam = cam(
    input_tensor=input_tensor,
    targets=targets
)[0]


rgb_img = np.array(image.resize((224,224))).astype(np.float32)/255

visualization = show_cam_on_image(
    rgb_img,
    grayscale_cam,
    use_rgb=True
)

plt.figure(figsize=(10,5))

plt.subplot(1,2,1)
plt.imshow(rgb_img)
plt.title("Original")

plt.subplot(1,2,2)
plt.imshow(visualization)
plt.title("Grad-CAM")

plt.show()